### ISSUE TITLE
Update codespell pc hook

### ISSUE THREAD

**Issue by l50** [l50/goproject#47]
We should use a conf file instead:

```yaml
- repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        entry: codespell -q 3 -f --config .hooks/codespell.conf
```

`codespell.conf`:

```yaml
[codespell]
skip = .git,.github,.hooks
quiet-level = 3
ignore-words-list = inout,ser
```
